language: ruby
cache: bundler
gemfile: Gemfile
before_install:
  - bundle install
  # - gem install bundler
script:
  - bundle exec jekyll algolia --config _config.yml

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true

branches:
  only:
    # Change this to gh-pages if you're deploying using the gh-pages branch
    - master
rvm:
 - 2.4